export type DemoImage = {
    id: string;
    url: string;
    tipo: 'hero' | 'gallery';
    orden: number;
};

export type DemoVehicle = {
    id: string;
    vin: string;
    marca: string;
    modelo: string;
    anio: number;
    precio: number;
    kilometraje: number;
    transmision: string;
    combustible: string;
    color: string;
    descripcion: string;
    estado: string;
    imagen_url: string;
    imagenes: DemoImage[];
    imagen_360_url: string;
    highlights: string[];
    badges: string[];
    inspeccion: { puntos: number; resumen: string };
    historial: { titulo: string; detalle: string }[];
};

const makeImages = (id: string): DemoImage[] => {
    const images: DemoImage[] = [{ id: `${id}-hero`, url: `/demo/vehicles/${id}/hero.jpg`, tipo: 'hero', orden: 1 }];
    for (let i = 1; i <= 9; i += 1) {
        images.push({
            id: `${id}-gallery-${i}`,
            url: `/demo/vehicles/${id}/gallery-${i}.jpg`,
            tipo: 'gallery',
            orden: i + 1,
        });
    }
    return images;
};

export const DEMO_PLACEHOLDER = '/demo/placeholder.jpg';

export const DEMO_VEHICLES: DemoVehicle[] = [
    {
        id: 'demo-1',
        vin: 'WVWZZZ1KZAP012345',
        marca: 'Volkswagen',
        modelo: 'Golf Trendline 1.6',
        anio: 2018,
        precio: 13900,
        kilometraje: 72000,
        transmision: 'Manual',
        combustible: 'Nafta',
        color: 'Azul',
        descripcion: 'Volkswagen Golf con mantenimiento al dia, llantas de aleacion y multimedia. Equilibrio ideal entre confort urbano y ruta.',
        estado: 'disponible',
        imagen_url: '/demo/vehicles/demo-1/hero.jpg',
        imagenes: makeImages('demo-1'),
        imagen_360_url: '/360/car-interior-1.jpg',
        highlights: ['Conectividad completa', 'Consumo eficiente', 'Frenos ABS + ESP', 'Llantas de aleacion'],
        badges: ['360', 'Certificado', 'Garantia 12m'],
        inspeccion: { puntos: 110, resumen: 'Inspeccion multipunto con reporte digital y garantia mecanica basica.' },
        historial: [
            { titulo: 'Service al dia', detalle: 'Mantenimientos registrados en tiempo y forma.' },
            { titulo: 'Kilometraje verificado', detalle: 'Lectura y trazabilidad confirmadas.' },
            { titulo: 'Unico dueno', detalle: 'Titularidad unica registrada.' },
        ],
    },
    {
        id: 'demo-2',
        vin: 'WME4513341K123456',
        marca: 'Smart',
        modelo: 'Forfour Brabus',
        anio: 2017,
        precio: 11200,
        kilometraje: 54000,
        transmision: 'Automatica',
        combustible: 'Nafta',
        color: 'Negro',
        descripcion: 'Smart Forfour con paquete Brabus. Compacto, agil y perfecto para ciudad con excelente equipamiento.',
        estado: 'disponible',
        imagen_url: '/demo/vehicles/demo-2/hero.jpg',
        imagenes: makeImages('demo-2'),
        imagen_360_url: '/360/car-interior-1.jpg',
        highlights: ['Automatica urbana', 'Radio con pantalla', 'Sensores de estacionamiento', 'Interior deportivo'],
        badges: ['360', 'Certificado', 'Garantia 6m'],
        inspeccion: { puntos: 95, resumen: 'Chequeo completo de motor, frenos y suspension.' },
        historial: [
            { titulo: 'Revisiones recientes', detalle: 'Service y filtros renovados.' },
            { titulo: 'Interior cuidado', detalle: 'Tapizado en excelente estado.' },
            { titulo: 'Documentacion al dia', detalle: 'Papeles listos para transferir.' },
        ],
    },
    {
        id: 'demo-3',
        vin: '1FTFW1E58JFB12345',
        marca: 'Ford',
        modelo: 'F-250 Lariat 4x4',
        anio: 2019,
        precio: 48900,
        kilometraje: 68000,
        transmision: 'Automatica',
        combustible: 'Diesel',
        color: 'Negro',
        descripcion: 'Pickup robusta para trabajo pesado y aventuras. Cabina doble, potencia y traccion integral.',
        estado: 'disponible',
        imagen_url: '/demo/vehicles/demo-3/hero.jpg',
        imagenes: makeImages('demo-3'),
        imagen_360_url: '/360/car-interior-2.jpg',
        highlights: ['4x4 con reductora', 'Capacidad de carga alta', 'Pantalla multimedia', 'Camara de retroceso'],
        badges: ['360', 'Certificado', 'Garantia 12m'],
        inspeccion: { puntos: 120, resumen: 'Inspeccion reforzada de tren delantero y suspension.' },
        historial: [
            { titulo: 'Uso mixto', detalle: 'Ruta y ciudad con mantenimiento documentado.' },
            { titulo: 'Neumaticos nuevos', detalle: 'Cambio reciente con balanceo.' },
            { titulo: 'Documentacion ok', detalle: 'Listo para entrega inmediata.' },
        ],
    },
    {
        id: 'demo-4',
        vin: 'WBA8B9C50JAB12345',
        marca: 'BMW',
        modelo: '330i M Sport',
        anio: 2021,
        precio: 46800,
        kilometraje: 29000,
        transmision: 'Automatica',
        combustible: 'Nafta',
        color: 'Blanco',
        descripcion: 'Sedan premium con paquete M Sport, faros LED, cuero y multimedia avanzada.',
        estado: 'disponible',
        imagen_url: '/demo/vehicles/demo-4/hero.jpg',
        imagenes: makeImages('demo-4'),
        imagen_360_url: '/360/car-interior-2.jpg',
        highlights: ['Paquete M Sport', 'Faros LED adaptativos', 'Asientos deportivos', 'Asistencias ADAS'],
        badges: ['360', 'Certificado', 'Garantia 12m'],
        inspeccion: { puntos: 150, resumen: 'Inspeccion premium con informe digital y garantia extendida.' },
        historial: [
            { titulo: 'Service oficial', detalle: 'Mantenimientos en taller autorizado.' },
            { titulo: 'Kilometraje bajo', detalle: 'Uso moderado y verificado.' },
            { titulo: 'Estado impecable', detalle: 'Detalle estetico completo.' },
        ],
    },
    {
        id: 'demo-5',
        vin: '3C3CFFKR1DT123456',
        marca: 'Fiat',
        modelo: '500 Lounge',
        anio: 2016,
        precio: 9800,
        kilometraje: 61000,
        transmision: 'Manual',
        combustible: 'Nafta',
        color: 'Gris',
        descripcion: 'Fiat 500 Lounge con techo panoramico, sensores de estacionamiento y diseno urbano.',
        estado: 'disponible',
        imagen_url: '/demo/vehicles/demo-5/hero.jpg',
        imagenes: makeImages('demo-5'),
        imagen_360_url: '/360/car-interior-1.jpg',
        highlights: ['Techo panoramico', 'Bluetooth y USB', 'Sensores traseros', 'Interior cuidado'],
        badges: ['360', 'Certificado', 'Garantia 6m'],
        inspeccion: { puntos: 90, resumen: 'Chequeo general de seguridad y mantenimiento.' },
        historial: [
            { titulo: 'Uso urbano', detalle: 'Bajo desgaste mecanico.' },
            { titulo: 'Documentos al dia', detalle: 'Transferencia inmediata.' },
            { titulo: 'Service reciente', detalle: 'Aceite y filtros al dia.' },
        ],
    },
    {
        id: 'demo-6',
        vin: 'WF0DP3TH6F4123456',
        marca: 'Ford',
        modelo: 'Focus SE',
        anio: 2018,
        precio: 12600,
        kilometraje: 83000,
        transmision: 'Manual',
        combustible: 'Nafta',
        color: 'Plata',
        descripcion: 'Ford Focus SE con excelente comportamiento en ruta, seguridad y conectividad.',
        estado: 'disponible',
        imagen_url: '/demo/vehicles/demo-6/hero.jpg',
        imagenes: makeImages('demo-6'),
        imagen_360_url: '/360/car-interior-1.jpg',
        highlights: ['Control de estabilidad', 'Bluetooth', 'Velocimetro digital', 'Buen consumo'],
        badges: ['360', 'Certificado', 'Garantia 6m'],
        inspeccion: { puntos: 100, resumen: 'Chequeo completo de frenos, suspension y motor.' },
        historial: [
            { titulo: 'Mantenimiento al dia', detalle: 'Registros disponibles.' },
            { titulo: 'Interior limpio', detalle: 'Sin desgaste notable.' },
            { titulo: 'Listo para entrega', detalle: 'Documentacion verificada.' },
        ],
    },
    {
        id: 'demo-7',
        vin: 'WBA8E9C52KAB12345',
        marca: 'BMW',
        modelo: '340i Touring',
        anio: 2020,
        precio: 52900,
        kilometraje: 34000,
        transmision: 'Automatica',
        combustible: 'Nafta',
        color: 'Negro',
        descripcion: 'Touring premium con gran espacio de carga, traccion integral y equipamiento deportivo.',
        estado: 'disponible',
        imagen_url: '/demo/vehicles/demo-7/hero.jpg',
        imagenes: makeImages('demo-7'),
        imagen_360_url: '/360/car-interior-3.jpg',
        highlights: ['AWD xDrive', 'Maletero amplio', 'Modo Sport', 'Sistema premium de audio'],
        badges: ['360', 'Certificado', 'Garantia 12m'],
        inspeccion: { puntos: 150, resumen: 'Inspeccion premium con cobertura extendida.' },
        historial: [
            { titulo: 'Service oficial', detalle: 'Mantenimientos en concesionario.' },
            { titulo: 'Kilometraje verificado', detalle: 'Informe disponible.' },
            { titulo: 'Estetica premium', detalle: 'Detalle interior y exterior.' },
        ],
    },
    {
        id: 'demo-8',
        vin: 'ZFF79ALA4J0234567',
        marca: 'Ferrari',
        modelo: '488 GTB',
        anio: 2019,
        precio: 245000,
        kilometraje: 12000,
        transmision: 'Automatica',
        combustible: 'Nafta',
        color: 'Rojo',
        descripcion: 'Superdeportivo con performance iconica. Potencia, sonido y presencia para clientes exigentes.',
        estado: 'disponible',
        imagen_url: '/demo/vehicles/demo-8/hero.jpg',
        imagenes: makeImages('demo-8'),
        imagen_360_url: '/360/car-interior-3.jpg',
        highlights: ['Motor V8 biturbo', 'Launch control', 'Frenos carbono', 'Asientos racing'],
        badges: ['360', 'Certificado', 'Garantia 12m'],
        inspeccion: { puntos: 160, resumen: 'Inspeccion de alto rendimiento con reporte premium.' },
        historial: [
            { titulo: 'Kilometraje muy bajo', detalle: 'Uso selectivo y controlado.' },
            { titulo: 'Estado coleccion', detalle: 'Detalle estetico completo.' },
            { titulo: 'Documentacion completa', detalle: 'Listo para entrega.' },
        ],
    },
    {
        id: 'demo-9',
        vin: 'JM1BPALM7K1234567',
        marca: 'Mazda',
        modelo: '3 Hatchback',
        anio: 2020,
        precio: 18900,
        kilometraje: 41000,
        transmision: 'Automatica',
        combustible: 'Nafta',
        color: 'Rojo',
        descripcion: 'Mazda 3 con diseno deportivo, seguridad avanzada y excelente confort de marcha.',
        estado: 'disponible',
        imagen_url: '/demo/vehicles/demo-9/hero.jpg',
        imagenes: makeImages('demo-9'),
        imagen_360_url: '/360/car-interior-2.jpg',
        highlights: ['Pantalla central', 'Asistencias ADAS', 'Conectividad completa', 'Bajo consumo'],
        badges: ['360', 'Certificado', 'Garantia 12m'],
        inspeccion: { puntos: 120, resumen: 'Inspeccion multipunto y garantia mecanica.' },
        historial: [
            { titulo: 'Service registrado', detalle: 'Mantenimientos documentados.' },
            { titulo: 'Unico dueno', detalle: 'Titularidad verificada.' },
            { titulo: 'Kilometraje real', detalle: 'Lectura certificada.' },
        ],
    },
    {
        id: 'demo-10',
        vin: 'WAUZZZ8K1DA123456',
        marca: 'Audi',
        modelo: 'A4 S line',
        anio: 2020,
        precio: 35900,
        kilometraje: 38000,
        transmision: 'Automatica',
        combustible: 'Nafta',
        color: 'Gris',
        descripcion: 'Audi A4 con paquete S line, interior premium y tecnologia de asistencia avanzada.',
        estado: 'disponible',
        imagen_url: '/demo/vehicles/demo-10/hero.jpg',
        imagenes: makeImages('demo-10'),
        imagen_360_url: '/360/car-interior-2.jpg',
        highlights: ['S line interior/exterior', 'Virtual cockpit', 'Asistencias ADAS', 'Audio premium'],
        badges: ['360', 'Certificado', 'Garantia 12m'],
        inspeccion: { puntos: 150, resumen: 'Chequeo premium con garantia extendida.' },
        historial: [
            { titulo: 'Service oficial', detalle: 'Mantenimientos en red autorizada.' },
            { titulo: 'Kilometraje bajo', detalle: 'Uso moderado.' },
            { titulo: 'Estado impecable', detalle: 'Detalle estandar premium.' },
        ],
    },
    {
        id: 'demo-11',
        vin: 'WDD2050421R123456',
        marca: 'Mercedes-Benz',
        modelo: 'C200',
        anio: 2019,
        precio: 33200,
        kilometraje: 46000,
        transmision: 'Automatica',
        combustible: 'Nafta',
        color: 'Plata',
        descripcion: 'Mercedes-Benz C200 con confort premium y gran equilibrio entre performance y elegancia.',
        estado: 'disponible',
        imagen_url: '/demo/vehicles/demo-11/hero.jpg',
        imagenes: makeImages('demo-11'),
        imagen_360_url: '/360/car-interior-2.jpg',
        highlights: ['Interior cuero', 'Asientos electricos', 'Climatizador dual', 'LED inteligente'],
        badges: ['360', 'Certificado', 'Garantia 12m'],
        inspeccion: { puntos: 150, resumen: 'Inspeccion premium con reporte digital.' },
        historial: [
            { titulo: 'Service oficial', detalle: 'Mantenimientos al dia.' },
            { titulo: 'Kilometraje verificado', detalle: 'Registro completo.' },
            { titulo: 'Exterior sin detalles', detalle: 'Estado estetico destacado.' },
        ],
    },
    {
        id: 'demo-12',
        vin: 'JTDBR32E742123456',
        marca: 'Toyota',
        modelo: 'Corolla XEi',
        anio: 2021,
        precio: 21900,
        kilometraje: 32000,
        transmision: 'Automatica',
        combustible: 'Nafta',
        color: 'Blanco',
        descripcion: 'Toyota Corolla XEi con confiabilidad y bajo costo de mantenimiento. Excelente para uso diario.',
        estado: 'disponible',
        imagen_url: '/demo/vehicles/demo-12/hero.jpg',
        imagenes: makeImages('demo-12'),
        imagen_360_url: '/360/car-interior-1.jpg',
        highlights: ['Consumo eficiente', 'Asistencias ADAS', 'Pantalla multimedia', 'Alta reventa'],
        badges: ['360', 'Certificado', 'Garantia 12m'],
        inspeccion: { puntos: 120, resumen: 'Chequeo general y garantia mecanica.' },
        historial: [
            { titulo: 'Service al dia', detalle: 'Mantenimientos registrados.' },
            { titulo: 'Uso familiar', detalle: 'Sin exigencias extremas.' },
            { titulo: 'Listo para entrega', detalle: 'Documentacion completa.' },
        ],
    },
    {
        id: 'demo-13',
        vin: '2HGFC2F59JH123456',
        marca: 'Honda',
        modelo: 'Civic Touring',
        anio: 2019,
        precio: 24500,
        kilometraje: 52000,
        transmision: 'Automatica',
        combustible: 'Nafta',
        color: 'Azul',
        descripcion: 'Honda Civic Touring con excelente calidad de rodaje, seguridad y confort premium.',
        estado: 'disponible',
        imagen_url: '/demo/vehicles/demo-13/hero.jpg',
        imagenes: makeImages('demo-13'),
        imagen_360_url: '/360/car-interior-2.jpg',
        highlights: ['Techo solar', 'Asistencias ADAS', 'Audio premium', 'Asientos calefaccionados'],
        badges: ['360', 'Certificado', 'Garantia 12m'],
        inspeccion: { puntos: 130, resumen: 'Inspeccion multipunto con cobertura extendida.' },
        historial: [
            { titulo: 'Service en regla', detalle: 'Registros actualizados.' },
            { titulo: 'Kilometraje verificado', detalle: 'Control documental.' },
            { titulo: 'Interior premium', detalle: 'Tapizados en excelente estado.' },
        ],
    },
    {
        id: 'demo-14',
        vin: '9BGKC48T0JG123456',
        marca: 'Chevrolet',
        modelo: 'Onix Premier',
        anio: 2022,
        precio: 16900,
        kilometraje: 28000,
        transmision: 'Automatica',
        combustible: 'Nafta',
        color: 'Gris',
        descripcion: 'Chevrolet Onix Premier con tecnologia completa y gran eficiencia de consumo.',
        estado: 'disponible',
        imagen_url: '/demo/vehicles/demo-14/hero.jpg',
        imagenes: makeImages('demo-14'),
        imagen_360_url: '/360/car-interior-1.jpg',
        highlights: ['Pantalla tactil', 'WiFi integrado', 'Camara trasera', 'Bajo consumo'],
        badges: ['360', 'Certificado', 'Garantia 12m'],
        inspeccion: { puntos: 120, resumen: 'Chequeo general con garantia mecanica.' },
        historial: [
            { titulo: 'Unico dueno', detalle: 'Titularidad verificada.' },
            { titulo: 'Service reciente', detalle: 'Aceite y filtros nuevos.' },
            { titulo: 'Documentacion al dia', detalle: 'Listo para transferir.' },
        ],
    },
    {
        id: 'demo-15',
        vin: 'VF3UJAUZXKJ123456',
        marca: 'Peugeot',
        modelo: '208 Allure',
        anio: 2021,
        precio: 15500,
        kilometraje: 42000,
        transmision: 'Manual',
        combustible: 'Nafta',
        color: 'Rojo',
        descripcion: 'Peugeot 208 Allure con diseno moderno, excelente confort y equipamiento completo.',
        estado: 'disponible',
        imagen_url: '/demo/vehicles/demo-15/hero.jpg',
        imagenes: makeImages('demo-15'),
        imagen_360_url: '/360/car-interior-1.jpg',
        highlights: ['Pantalla multimedia', 'Sensores traseros', 'Control de estabilidad', 'Buen consumo'],
        badges: ['360', 'Certificado', 'Garantia 12m'],
        inspeccion: { puntos: 115, resumen: 'Inspeccion multipunto y garantia mecanica.' },
        historial: [
            { titulo: 'Service al dia', detalle: 'Registros de mantenimiento.' },
            { titulo: 'Kilometraje verificado', detalle: 'Informe disponible.' },
            { titulo: 'Estado general muy bueno', detalle: 'Interior y exterior cuidados.' },
        ],
    },
];

export const DEMO_VEHICLES_MAP = DEMO_VEHICLES.reduce<Record<string, DemoVehicle>>((acc, vehiculo) => {
    acc[vehiculo.id] = vehiculo;
    return acc;
}, {});

export function getDemoVehicleById(id: string | null | undefined): DemoVehicle | undefined {
    if (!id) return undefined;
    return DEMO_VEHICLES_MAP[id];
}
